#
###################################
# Site wide configuration
####################################
#
title: Sahista Gurung Portfolio
email: sahistagurung@gmail.com
description: "Portfolio of Sahista Gurung – Artist and Student."
url: "https://sahistagurung.github.io/sahistagurungart.github.io"
baseurl: ""
keywords: ["art portfolio", "fine arts", "illustration", "Sahista Gurung", "student artist"]

#
###################################
# Jekyll configuration
####################################
#
timezone: Europe/Paris
markdown: kramdown
highlighter: rouge
excerpt_separator: ""
permalink: "/articles/:year-:month/:title"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Sahista Gurung
  avatar: sahistagurung.jpeg
  job: "Artist & AI Student"
  bio: "Exploring life through art and tech."
  disqus-shortname:
  facebook: https://www.facebook.com/sahistaagurung/
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sahistagurung
  linkedin: sahistagurung
  instagram: sahistagurung
  pinterest: sahistagurung